### ISSUE TITLE
How to run/use

### ISSUE THREAD

**Issue by spacemanidol** [abhishekkrthakur/is_that_a_duplicate_quora_question#1]
Hey,

First of awesome article and idea. 
I have been trying to get your demo up and running but have been struggling. 
So far I have installed the following packages but still get the following errors when trying to run either of the files 

```
python deepnet.py

  File "deepnet.py", line 19, in <module>
    y = data.is_duplicate.values
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 2744, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'is_duplicate'
```

```
python feature_engineering.py
/usr/local/lib/python2.7/dist-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "feature_engineering.py", line 58, in <module>
    data['len_q1'] = data.question1.apply(lambda x: len(str(x)))
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 2744, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'question1'

```
whats the setup for the environment and how do you run/use the tooling.

**Comment by spacemanidol** [comment]
update. The most recent dataset from Quora has different headers. So option one is to change the file to have matching headers or to change the code to match the file. E.G. data uses text1 and text2 and code uses question1 and question2

**Comment by abhishekkrthakur** [comment]
I downloaded the data a while ago. will fix with the new data.

**Comment by spacemanidol** [comment]
ive update the files and added some info to the readme. I can push if you give me access to the repo

**Comment by abhishekkrthakur** [comment]
Please make a pull request

**Comment by spacemanidol** [comment]
file has been changed back to original formating by quora and i updated the usage of word2vec
