### ISSUE TITLE
why is the embedding matrix not passed for embedded layer weights in model 5 & 6?

### ISSUE THREAD

**Issue by bbc4468** [abhishekkrthakur/is_that_a_duplicate_quora_question#6]
Why are we learning the embeddings in model 5 & 6 and not passing the glove embeddings?

**Comment by abhishekkrthakur** [comment]
2 were with glove and 2 without glove. thats a part of the model that i came up with. :)

**Comment by bbc4468** [comment]
@abhishekkrthakur Can you throw some more light on how did you come up with the model. Was it hit and trial or is there some logic behind the design? Do you think the complexity of the model can be reduced without compromising on the accuracy?
